version: 2

models:
  - name: stg_game_economy
    description: "Cleaned data on transactions and currency spending in the game"
    columns:
      - name: event_id
        description: "Unique ID of the event"
        tests:
          - unique
          - not_null
      - name: currency
        tests:
          - accepted_values:
              arguments:
                values: ['hard_gem', 'soft_coin']
                quote: true

  - name: stg_game_sessions
    columns:
      - name: event_id
        tests:
          - unique
          - not_null